# ----- SERVIDOR -----
server.port=8080
spring.application.name=taskmaster

# ----- SQLITE -----
spring.datasource.url=jdbc:sqlite:${user.home}/.taskmaster/taskmaster.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# ----- JPA -----
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.properties.hibernate.connection.foreign_keys=true
spring.jpa.open-in-view=false

# ----- LOGS -----
logging.level.com.taskmaster=DEBUG
logging.level.org.springframework.security=DEBUG

# ----- ALMACENAMIENTO DE AVATARES -----
taskmaster.storage.avatars-dir=${user.home}/.taskmaster/avatars

# ----- MULTIPART -----
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB